logging.level:
  org.springframework.security: DEBUG
  io.github.ssledz: DEBUG
  root: INFO

facebook:
  client:
    clientId: override me !
    clientSecret: override me !
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: override me !
    clientSecret: override me !
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

keycloak:
  client:
    clientId: override me !
    clientSecret: override me !
    accessTokenUri: http://localhost:9080/auth/realms/dev/protocol/openid-connect/token
    userAuthorizationUri: http://localhost:9080/auth/realms/dev/protocol/openid-connect/auth
    Scope: openid
    grantType: client_credentials
  resource:
    userInfoUri: http://localhost:9080/auth/realms/dev/protocol/openid-connect/userinfo
    token-info-uri: http://localhost:9080/auth/realms/dev/protocol/openid-connect/token/introspect